# ESCREVA UM CÓDIGO EM ASSEMBLY MIPS
# QUE LEIA DOIS VALORES NUMÉRICOS INTEIROS E, 
# EM SEGUIDA, A OPERAÇÃO A SER REALIZADA ENTRE
# ELES (SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO OU DIVISÃO)
# CASO O USUÁRIO DIGITE "0", O PROGRAMA DEVERÁ SER ENCERRADO